### ISSUE TITLE
Error on starting, followed directions in readme

### ISSUE THREAD

**Issue by imtammer** [FoxxMD/discord-overseer-info#1]
discord-overseer-info-1  |     baseUrl: Config.overseer.baseUrl,
discord-overseer-info-1  | [2024-09-08 19:30:52.690] ERROR: An unhandled promise rejection occurred.
discord-overseer-info-1  |     err: {
discord-overseer-info-1  |       "type": "DiscordjsError",
discord-overseer-info-1  |       "message": "Shard 0's process exited before its Client became ready.",
discord-overseer-info-1  |       "stack":
discord-overseer-info-1  |           Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.
discord-overseer-info-1  |               at Shard.onDeath (/app/node_modules/discord.js/src/sharding/Shard.js:178:16)
discord-overseer-info-1  |               at Object.onceWrapper (node:events:632:26)
discord-overseer-info-1  |               at Shard.emit (node:events:517:28)

discord-overseer-info-1  |               at Shard._handleExit (/app/node_modules/discord.js/src/sharding/Shard.js:439:10)
discord-overseer-info-1  |               at ChildProcess.emit (node:events:517:28)

discord-overseer-info-1  |               at ChildProcess._handle.onexit (node:internal/child_process:292:12)
discord-overseer-info-1  |       "code": "ShardingReadyDied"
discord-overseer-info-1  |     }

discord-overseer-info-1  |                              ^

discord-overseer-info-1  |
discord-overseer-info-1  | TypeError: Cannot read properties of undefined (reading 'baseUrl')

discord-overseer-info-1  |     at file:///app/dist/commands/chat/movie-command.js:11:30
discord-overseer-info-1  |     at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
discord-overseer-info-1  |     at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
discord-overseer-info-1  |     at async loadESM (node:internal/process/esm_loader:34:7)
discord-overseer-info-1  |     at async handleMainPromise (node:internal/modules/run_main:106:12)
discord-overseer-info-1  | 
discord-overseer-info-1  | Node.js v18.20.4

discord-overseer-info-1  | file:///app/dist/commands/chat/movie-command.js:11
discord-overseer-info-1  |     baseUrl: Config.overseer.baseUrl,
discord-overseer-info-1  |                              ^
discord-overseer-info-1  | 
discord-overseer-info-1  | TypeError: Cannot read properties of undefined (reading 'baseUrl')
discord-overseer-info-1  |     at file:///app/dist/commands/chat/movie-command.js:11:30
discord-overseer-info-1  |     at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
discord-overseer-info-1  |     at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
discord-overseer-info-1  |     at async loadESM (node:internal/process/esm_loader:34:7)
discord-overseer-info-1  |     at async handleMainPromise (node:internal/modules/run_main:106:12)

**Comment by FoxxMD** [comment]
Can you please try this...

Get API Key from Overseer:

* Open your Overseer instance
* Go to settings -> general
  * Copy **API Key**

Copy Overseer Settings to `config.json`

In the [`config.json` files created in the instructions](https://github.com/FoxxMD/discord-overseer-info?tab=readme-ov-file#create-bot-config) change:

* Update `overseer.apiKey` with the API Key copied earlier
* Update `baseUrl` to `YOUR_INSTANCE/api/v1`
  * Example -> you access overseer at `http://192.168.0.100:5055` then `baseUrl` is `http://192.168.0.100:5055/api/v1`
